<?php
define("ID_MAILING_FORM_TEMPLATE", 71);
define("FEEDBACK_IBLOCK_ID", 5);
define("NEWS_IBLOCK_ID", 6);
define('RE_CAPTCHA_SITE_KEY', 'YOU-CAPTCHA-SITE-KEY');
define('RE_CAPTCHA_SECRET_KEY', 'YOU-CAPTCHA-SECRET-KEY');